# Generated by Django 5.1.1 on 2024-10-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('network_equipment', models.TextField(blank=True)),
                ('peripheral_equipment', models.TextField(blank=True)),
                ('other_info', models.TextField(blank=True)),
            ],
        ),
    ]
